{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

{{- if .Values.fabric_actions.cryptogen }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fabric-ops.fullname" $ }}
  labels:
    {{- include "fabric-ops.labels" $ | nindent 4 }}
spec:
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fabric-ops.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fabric-ops.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never  
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          workingDir: /scripts
          command: ["/bin/sh","-c"]
          args:
            - /scripts/cryptogen.sh;
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          env:
            - name: FABRIC_CFG_PATH
              value: /scripts
          volumeMounts:
            - name: configtx
              subPath: configtx.yaml
              mountPath: /scripts/configtx.yaml
            - name: scripts
              subPath: cryptogen.sh
              mountPath: /scripts/cryptogen.sh
            - name: fabric-ops
              subPath: config.yaml
              mountPath: /tmp/config.yaml
            - name: fabric-ops
              subPath: fabric_enroll.sh
              mountPath: /scripts/fabric_enroll.sh
      volumes:
        - name: configtx
          configMap:
            name: {{ include "fabric-ops.fullname" $ }}-configtx
            defaultMode: 0777
        - name: scripts
          configMap:
            name: {{ include "fabric-ops.fullname" $ }}
            defaultMode: 0777
        - name: fabric-ops
          configMap:
            name: {{ include "fabric-ops.fullname" $ }}-functions
            defaultMode: 0777
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}