{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: 
    {{- include "fabric-ops.labels" $ | nindent 4 }}
  annotations: {}
  name: {{ include "fabric-ops.fullname" . }}
rules:
  - apiGroups: [""]
    resources: [""]
    verbs: [""]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: 
    {{- include "fabric-ops.labels" $ | nindent 4 }}
  annotations: {}
  name: {{ include "fabric-ops.fullname" . }}
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: {{ include "fabric-ops.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fabric-ops.fullname" . }}
