{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

{{ $BankName               := .Values.nameOverride }}
{{ $CorePeerMspConfigPath  := printf "%s%s" .Values.workdir "/crypto/users/admin/msp" }}
{{ $TlsCaTlsCertFile       := .Values.tlsca_tls_certfile | default "/tmp/tlsca-cert.pem" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fabric-tools.fullname" . }}
  labels:
    {{- include "fabric-tools.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fabric-tools.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fabric-tools.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fabric-tools.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: cli
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: {{ $.Values.workdir }}/peer
          tty: true
          env: 
            - name: CLUSTER_DOMAIN
              value: {{ .Values.hlf_domain }}
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: CORE_PEER_LOCALMSPID
              value: {{ $BankName }}
            - name: CORE_PEER_MSPCONFIGPATH
              value: {{ $.Values.core_peer_mspconfigpath_override | default $CorePeerMspConfigPath }}
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: {{ $TlsCaTlsCertFile }}
            - name: GOPATH
              value: /opt/gopath
            - name: ORDERER_CA
              value: {{ $TlsCaTlsCertFile }}
          volumeMounts:
            - name: data
              mountPath: {{ $.Values.workdir }}
            - name: fabric-ops
              subPath: config.yaml
              mountPath: /tmp/config.yaml
            - name: fabric-ops
              subPath: enroll.sh
              mountPath: /scripts/enroll.sh
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: fabric-ops
          configMap:
            name: {{ include "fabric-tools.fullname" $ }}-fabric-ops
            defaultMode: 0777
        - name: data
          persistentVolumeClaim:
            claimName: data-{{ include "fabric-tools.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}