{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-{{ include "fabric-tools.fullname" . }}
  labels:
    {{- include "fabric-tools.labels" $ | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.tools.storageAccessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.tools.storageSize | default "5Gi" }}
  storageClassName: {{ .Values.tools.storageClass | default "default" }}