# Copyright National Payments Corporation of India. All Rights Reserved.
# SPDX-License-Identifier:  GPL-3.0
# Default values for fabric-peer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# peers:
#   - name: peer0
#     identity_name: peer0-org
#     identity_secret: peer0orgSamplePassword
#     couchUseExistingPvcPrefix: couch-pvc # If you want to use an existing pvc for Couch. A pvc must exists with name couch-pvc-peer0-org-0
#     peerUseExistingPvcPrefix: peer-pvc # If you want to use an existing pvc for Peer. A pvc must exists with name peer-pvc-peer0-org-0
#     dindUseExistingPvcPrefix: dind-pvc # If you want to use an existing pvc for Dind. A pvc must exists with name dind-pvc-peer0-org1-0
#     require_certs_dir_persistence: true # If you want PVC to store the msp/tls certs.
#     renew_peer_certs: true # If you want to generate new msp/tls certificates on the next reboot.
#     #Add additional env variables unique to this peer
#     additionalEnvironmentVars:
#      peer:
#      - name: PEER_ENV_NAME
#        value: peer_env_value
#      dind:
#      - name: DIND_ENV_NAME
#        value: dind_env_value
#      couchDb:
#      - name: COUCHDB_ENV_NAME
#        value: couchdb_env_value
#     # Additional labels unique for this peer  
#     additionalLabels:
#       extraPeerLabel1: extraPeerLabelvalue1
#       extraPeerLabel2: extraPeerLabelvalue2
fabric_base_dir: /etc/hyperledger/fabric
retry_seconds: 60

couchStartupProbe:
  failureThreshold: 3
  periodSeconds: 10
  tcpSocket:
    port: 5984
  initialDelaySeconds: 20
couchLivenessProbe:
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 5984
couchReadinessProbe:
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 5984

peerStartupProbe:
  failureThreshold: 3
  periodSeconds: 10
  tcpSocket:
    port: 7051
  initialDelaySeconds: 20
peerLivenessProbe:
  failureThreshold: 3
  httpGet:
    path: /healthz
    port: 9443
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
peerReadinessProbe:
  failureThreshold: 3
  httpGet:
    path: /healthz
    port: 9443
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1

dindStartupProbe:
  failureThreshold: 3
  periodSeconds: 10
  tcpSocket:
    port: 2375
  initialDelaySeconds: 20 
dindLivenessProbe:
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 2375
dindReadinessProbe:
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 2375

podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


