{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "filestore.fullname" . }}
  labels:
    {{- include "filestore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "filestore.selectorLabels" . | nindent 4 }}